---
title: "Gouvdown - Une implémentation de la marque État"
subtitle: "Rencontres R 2021"
author:
- Romain Lesur (INSEE)
- Maël Theulière (DREAL Pays-de-la-Loire)
- Thomas Vroylandt (Tillac)
output:
  xaringan::moon_reader:
    css: "gouvdown_xaringan.css"
---
class: inverse, center, middle

# Pourquoi {gouvdown} ?
---

## La marque-État

+ Une présence de l'État modernisée : " Là où l’État est présent, agit, finance, sa présence doit être clairement identifiée."

+ Un jeu de couleurs

IMAGE

+ Des typographiques (dont la Marianne)

IMAGE

+ Des blocs-marques déclinables par institution

+ Pour en savoir plus : https://www.gouvernement.fr/marque-Etat

---

## Construire un package

+ De nombreux utilisateurs de R dans la sphère publique

+ Implémenter une charte graphique demande un certain investissement

+ Un package permet une utilisation facilitée

+ Sans devoir plonger dans les détails

---

## L'inspiration anglaise : {govdown}

EXEMPLE FORMAT

+ https://ukgovdatascience.github.io/govdown/

---
class: inverse, center, middle

# Qui a-t-il dedans ?

---

## Éléments graphiques

+ palettes

+ thèmes {ggplot2} (normaux et cartes)

+ Doc : https://spyrales.github.io/gouvdown/articles/graph_gouv.html

---

## RMarkdown

Différents templates

+ Web

IMAGE

+ {pagedown}, doc : (UNE FOIS LA PR MERGED)

IMAGE

+ {xaringan} --> a intégrer depuis CSS

---

## Utilitaires

+ Intégration des polices

+ Blocs-marques

IMAGE

---
class: inverse, center, middle

# Et ça sert à quoi ?

---

## Liste d'exemples

+ démarche PROPRE --> renvoi vers l'autre présentation
+ http://www.donnees.pays-de-la-loire.developpement-durable.gouv.fr/publications/ecln/ECLN_Conj_2020T3.html (capture écran TODO)

---
class: inverse, center, middle

# Et ensuite ?

---

## Encore des bouts à développer

+ d'autres formats Markdown

+ Shiny [-> issue ici](https://github.com/spyrales/gouvdown/issues/7)

## Une utilisation à diffuser

+ Besoin d'utilisations et de reprises dans différents contextes

+ Ce n'est jamais qu'un package "support" de réalisations plus belles

## Ouverture aux contributions

Les contributions sont ouvertes à tous.

---
# Liens

+ Documentation : https://spyrales.github.io/gouvdown/index.html

+ Github : https://github.com/spyrales/gouvdown/
